language: haskell
install:
  - cabal install containers pretty-show vector
script:
  - cd MusicBrainz-libdiscid
  - cabal configure && cabal build && cabal install
  - cd ../MusicBrainz-libdiscid-test
  - cabal configure && cabal build
